version: 1.0.{build}

platform:
  - x64

clone_folder:  c:\projects\php-opencv

install:
  ps: |
    echo "Install OpenCV..."
    git clone https://github.com/opencv/opencv.git --branch $env:OPENCV_VERSION --depth 1  2>&1
    git clone https://github.com/opencv/opencv_contrib.git --branch $env:OPENCV_VERSION --depth 1  2>&1
    cd opencv
    mkdir build
    cd build
    pwd
    cmake -D CMAKE_BUILD_TYPE=RELEASE  -G "Visual Studio 15 2017 Win64" -D INSTALL_C_EXAMPLES=OFF -D OPENCV_PYTHON_SKIP_DETECTION=ON -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_JAVA=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D BUILD_TESTS=OFF -D BUILD_DOCS=OFF -D BUILD_opencv_world=ON -D OPENCV_EXTRA_MODULES_PATH=c:/projects/php-opencv/opencv_contrib/modules ..  2>&1
    cmake --build . --target INSTALL --config Release

build_script:
  - cmd: cmake --version

environment:
  OPENCV_VERSION: 4.0.0 # OpenCV 版本
  BIN_SDK_VER: 2.1.2 # 定义php-sdk-binary-tools 版本
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.2.3
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.2.3
      TS: 1
